apiVersion: v1
kind: ServiceAccount
metadata:
  name: edge-proxy-service-account 
  namespace: ecommerce
---
apiVersion: v1
kind: Service
metadata:
  name: edge-proxy
  namespace: ecommerce
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: external
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: instance
    external-dns.alpha.kubernetes.io/hostname: envoytest.spirenested.example.com
spec:
  selector:
    app: edge-proxy
  type: LoadBalancer
  ports:
  - protocol: TCP
    name: service-proxy-listener
    port: 8081
    targetPort: 8081
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: edge-proxy
  namespace: ecommerce
spec:
  replicas: 1
  selector:
    matchLabels:
      app: edge-proxy
      workload: ecommerce
  template:
    metadata:
      labels:
        app: edge-proxy
        workload: ecommerce
    spec:
      serviceAccountName: edge-proxy-service-account
      containers:
      - name: envoy
        image: envoyproxy/envoy:v1.25.7
        imagePullPolicy: Always
        args: ["-l", "debug", "--local-address-ip-version", "v4", "-c", "/run/envoy/envoy.yaml", "--base-id", "2"]
        ports:
        - containerPort: 8081
        volumeMounts:
        - name: envoy-config
          mountPath: "/run/envoy"
          readOnly: true 
        - name: spire-agent-socket-dir
          mountPath: /run/spire/agent-sockets
          readOnly: true
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 512Mi
      volumes:
      - name: envoy-config
        configMap:
          name: edge-envoy-config
      - name: spire-agent-socket-dir
        hostPath:
          path: /run/spire/agent-sockets
          type: DirectoryOrCreate